apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: aerial
servers: 1
agents: 2
image: rancher/k3s:v1.33.6-k3s1
network: aerial-net
options:
  k3d:
    wait: true
    timeout: "120s"
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters: [server:*]
      - arg: --disable=servicelb
        nodeFilters: [server:*]
      - arg: --tls-san=host.docker.internal
        nodeFilters: [server:*]
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
ports:
  # Open5GS WebUI (subscriber CRUD)
  - port: 127.0.0.1:9999:30099
    nodeFilters: [server:*]
volumes:
  - volume: /tmp/aerial-shared:/aerial-shared
    nodeFilters: [server:*, agent:*]
registries:
  create:
    name: aerial-registry
    host: "0.0.0.0"
    hostPort: "5005"
